openapi: "3.0.0"
info:
    title: JFR API
    version: 1.0.0
    description: API for persisting JFR data
servers:
    - url: http://localhost:8080
paths:
    /jfr:
        post:
            tags:
                - JFR
            summary: Save a new JFR file
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                file:
                                    type: array
                                    items:
                                        type: string
                                        format: binary
                                commitValue:
                                    type: string
                                date:
                                    type: string
                                    format: date-time
            responses:
                '200':
                    description: File saved successfully
                '400':
                    description: Error saving the file
                '500':
                    description: Internal server error
    /statistics:
        post:
            tags:
                - Statistics
            summary: Get the statistics of an event on different commits
            parameters:
                - in: query
                  name: event
                  required: true
                  schema:
                    type: string
                - in: query
                  name: column
                  required: false
                  schema:
                    type: string
            responses:
                '200':
                    description: Difference calculated successfully
                '400':
                    description: Error calculating the difference
                '500':
                    description: Internal server error
    /events:
        get:
            tags:
                - Events
            summary: Get all events
            responses:
                '200':
                    description: Events retrieved successfully
                '400':
                    description: Error retrieving the events
                '500':
                    description: Internal server error
    /events/{event}:
        get:
            tags:
                - Events
            summary: Get all columns for a specific event
            parameters:
                - in: path
                  name: event
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Columns retrieved successfully
                '400':
                    description: Error retrieving the columns
                '500':
                    description: Internal server error

components:
    schemas:
        JFR:
            type: object
