openapi: "3.0.0"
info:
    title: JFR API
    version: 1.0.0
    description: API for persisting JFR data
servers:
    - url: http://localhost:8080
paths:
    /jfr:
        post:
            summary: Save a new JFR file
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                file:
                                    type: array
                                    items:
                                        type: string
                                        format: binary
                                commitValue:
                                    type: string
            responses:
                '200':
                    description: File saved successfully
                '400':
                    description: Error saving the file
                '500':
                    description: Internal server error

components:
    schemas:
        JFR:
            type: object
